/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bandcontrols;

import javax.swing.WindowConstants;

/**
 *
 * @author ksurctofficers
 */
public class StartGUI extends javax.swing.JFrame {

    
    // GUI Controller for access to model.
    public static GUIController controller;
    
    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
        controller = new GUIController();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uxProgramSoftwareButton = new javax.swing.JButton();
        uxRunButton = new javax.swing.JButton();
        uxConfigHWButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uxProgramSoftwareButton.setText("Program Software");
        uxProgramSoftwareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxProgramSoftwareButtonActionPerformed(evt);
            }
        });

        uxRunButton.setText("Run");
        uxRunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxRunButtonActionPerformed(evt);
            }
        });

        uxConfigHWButton.setText("Configure Hardware");
        uxConfigHWButton.setDoubleBuffered(true);
        uxConfigHWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxConfigHWButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uxRunButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uxConfigHWButton, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxProgramSoftwareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uxProgramSoftwareButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(uxConfigHWButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(uxRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens a window to configure the hardware (list of band members).
     * TODO: Figure out how to stop closing of the ConfigGUI closing the StartGUI.
     * @param evt 
     */
    private void uxConfigHWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxConfigHWButtonActionPerformed
        ConfigGUI config = new ConfigGUI();
        config.setVisible(true);
    }//GEN-LAST:event_uxConfigHWButtonActionPerformed

    /**
     * Opens a window to configure the software (set number, instrument type, instrument #, and color).
     * TODO: Figure out how to stop closing of the DesignGUI closing the StartGUI.
     * @param evt 
     */
    private void uxProgramSoftwareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxProgramSoftwareButtonActionPerformed
        DesignGUI design = new DesignGUI();
        design.setVisible(true);
    }//GEN-LAST:event_uxProgramSoftwareButtonActionPerformed

    /**
     * Opens a window to run the show (Load set, edit script, send to XBees).
     * TODO: Figure out how to stop closing of the RunGUI closing the StartGUI.
     * @param evt 
     */
    private void uxRunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxRunButtonActionPerformed
        RunGUI run = new RunGUI();
        run.setVisible(true);
    }//GEN-LAST:event_uxRunButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton uxConfigHWButton;
    private javax.swing.JButton uxProgramSoftwareButton;
    private javax.swing.JButton uxRunButton;
    // End of variables declaration//GEN-END:variables
}
